server:
  port: 8084
spring:
  application:
    name: payment
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://34.201.191.117:8761/eureka
