server:
  port: 8084
spring:
  application:
    name: payment

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://3.133.190.144:8761/eureka